In [1]:
name = 'Ben Mathew'
age = 20
print(name, age)

Ben Mathew 20


In [2]:
X = 'Datascience is used to extract meaningful insights.'
print(X.split())

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [6]:
def multiply_two_numbers(a, b):
    return a * b

a = int(input('Enter a: '))
b = int(input('Enter b: '))
print('The product =', multiply_two_numbers(a, b))

Enter a: 3
Enter b: 4
The product = 12


In [9]:
indian_states_capitals = {
    'Maharashtra': 'Mumbai',
    'Karnataka': 'Bengaluru',
    'Tamil Nadu': 'Chennai',
    'Uttar Pradesh': 'Lucknow',
    'Gujarat': 'Gandhinagar'
}

# Print the keys
print("Indian States:")
for state in indian_states_capitals.keys():
    print(state)

# Print the values
print("\nCapitals:")
for capital in indian_states_capitals.values():
    print(capital)

Indian States:
Maharashtra
Karnataka
Tamil Nadu
Uttar Pradesh
Gujarat

Capitals:
Mumbai
Bengaluru
Chennai
Lucknow
Gandhinagar


In [12]:
list = range(1000)
list[999]

999

In [1]:
import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

sum_array = array1 + array2
print(sum_array)

[[ 6  8]
 [10 12]]


In [6]:
import pandas as pd

date_range = pd.date_range(start='2023-02-01', end='2023-03-01', inclusive='left')
print(date_range)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28'],
              dtype='datetime64[ns]', freq='D')


In [8]:
import pandas as pd

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
